In [13]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from data import get_mnist


w = weights, b = bias, i = input, h = hidden, o = output, l = label
e.g. w_i_h = weights from input layer to hidden layer

In [14]:
images, labels = get_mnist()

w_i_h = np.random.uniform(-0.5, 0.5, (20, 784))
w_h_o = np.random.uniform(-0.5, 0.5, (10, 20))
b_i_h = np.zeros((20, 1))
b_h_o = np.zeros((10, 1))

learn_rate = 0.01
nr_correct = 0
epochs = 3
# how often we go through each image
epochs = 3
for epoch in range(epochs):
    # going through each image, label pair
    for img, l in zip(images, labels):
        # changes the shape of the img from a vector with size 784 to a matrix (784 * 1)
        img.shape += (1,)
        # changes the label from a vector with size 10 to a matrix (10 * 1)
        l.shape += (1,)
        
        # forward propagation input -> hidden and activation function (normalizing)  
        h_pre = (w_i_h @ img) + b_i_h
        h = 1 / (1 + np.exp(-h_pre))
        # forward propagation hidden -> output and activation function (normalizing)
        o_pre = (w_h_o @ h) + b_h_o
        o = 1 / (1 + np.exp(-o_pre))

        # cost (error) calculation
        error = 1 / len(o) * np.sum((o - l) ** 2, axis=0)
        # how many it got correct?
        nr_correct += np.sum(np.argmax(o, axis=0) == np.argmax(l, axis=0))


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
